### ISSUE TITLE
Mac OS X not supported?

### ISSUE THREAD

**Issue by sebastiaanluca** [pellegre/libcrafter-examples#1]
I tried to compile a working set of files I could use in C++, but it has some missing files so the "make install …" commands never produce anything I can use. So it's only Linux then, or am I missing something?

```
In file included from crafter/Packet.h:38,
                 from crafter/Packet.cpp:30:
crafter/Utils/RawSocket.h:39:22: error: features.h: No such file or directory
crafter/Utils/RawSocket.h:40:29: error: linux/if_packet.h: No such file or directory
crafter/Utils/RawSocket.h:41:28: error: linux/if_ether.h: No such file or directory
In file included from crafter/Packet.h:38,
                 from crafter/Packet.cpp:30:
crafter/Utils/RawSocket.h:68: error: ‘ETH_P_ALL’ was not declared in this scope
crafter/Utils/RawSocket.h:69: error: ‘ETH_P_ALL’ was not declared in this scope
make[1]: *** [crafter/Packet.lo] Error 1
make: *** [all] Error 2
```

**Comment by mikeguidry** [comment]
pc:libcrafter mike$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: /opt/local/bin/aclocal --force ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /opt/local/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory `.'
./configure: line 1: syntax error near unexpected token `('
./configure: line 1: `m4trace:configure.ac:4: -1- AC_INIT([libcrafter], [0.3], [pellegre.esteban@gmail.com], [crafter], [http://code.google.com/p/libcrafter/])'
pc:libcrafter mike$

I had this error on the OSX attempting to use autogen..

**Comment by brifordwylie** [comment]
@mikeguidry so at least on my mac sierra (10.12.3) this worked for me.

```
$ brew install autoconf libtool  automake
$ ./autogen.sh
$ make
$ make install
```

**Comment by milti** [comment]
im running macOS catalina: autogen.sh is failing on finding libpcap:

,,,:libcrafter ...$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
....
hecking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin19.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for u_int32_t... yes
checking for u_int64_t... yes
checking for u_int16_t... yes
checking for u_int8_t... yes
checking for size_t... yes
checking for libpcap... no
configure: error: libpcap not found

any suggestions on correcting?
